# Generated by Django 4.2 on 2025-07-15 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refrigerator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='complete',
            field=models.IntegerField(default=0, verbose_name='完了フラグ'),
        ),
    ]
