# Generated by Django 4.2 on 2025-07-15 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('refrigerator', '0002_ingredient_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='complete',
        ),
    ]
