# Generated by Django 4.2 on 2025-07-28 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refrigerator', '0003_remove_ingredient_complete'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('ingredients', models.TextField(max_length=1000)),
            ],
        ),
    ]
