# Generated by Django 4.2 on 2025-08-05 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refrigerator', '0005_remove_recipe_ingredients_recipe_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='memo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
